name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.0

    - name: No formatting changes
      run: |
        make format
        git diff --exit-code

    - name: Mocks up to date
      run: |
        go install go.uber.org/mock/mockgen@latest
        make generate-mocks
        git diff --exit-code

    - name: Test
      run: make test
